services:
  app:
    build:
      dockerfile: backend/Dockerfile
    container_name: Ai_challenge_app
    command: "python3 app.py"
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: Ai_challenge_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  app: